name: flutter_doctors_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <=3.3.10"

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.1.0
  dio: ^4.0.6
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.4
  intl: ^0.18.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  package_info_plus: ^1.4.2
  permission_handler: ^10.0.0
  persistent_bottom_nav_bar: ^5.0.2
 
  pull_to_refresh: ^2.0.0
  retrofit: '>=3.0.0 <4.0.0'
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.4
  uuid: ^3.0.6
#
#dependency_overrides:
#  analyzer: ">=4.3.1 <5.4.0"

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.11
  flutter_flavorizr: ^2.1.3
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.5.4
  pigeon: ^9.0.1
  retrofit_generator: ^4.2.0

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Flutter App Demo Dev"
      android:
        applicationId: "com.doctors.demo.dev"
      ios:
        bundleId: "com.doctors.demo.dev"

    staging:
      app:
        name: "Flutter App Demo Stg"
      android:
        applicationId: "com.doctors.demo.stg"
      ios:
        bundleId: "com.doctors.demo.stg"

    production:
      app:
        name: "Flutter App Demo Pro"
      android:
        applicationId: "com.doctors.demo.pro"
      ios:
        bundleId: "com.doctors.demo.pro"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  uses-material-design: true

  fonts:
    - family: SFProTextRegular
      fonts:
        - asset: assets/fonts/SF-ProText-Regular.ttf

  assets:
    - assets/
