// Autogenerated from Pigeon (v9.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by NavigationAPI.
NSObject<FlutterMessageCodec> *NavigationAPIGetCodec(void);

@protocol NavigationAPI
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)navigateWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)passDataValue:(NSString *)value error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void NavigationAPISetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NavigationAPI> *_Nullable api);

NS_ASSUME_NONNULL_END
